@startuml ER

!define MAIN_ENTITY #E2EFDA-C6E0B4
!define MAIN_ENTITY_2 #FCE4D6-F8CBAD

!define MASTER_MARK_COLOR AAFFAA
!define TRANSACTION_MARK_COLOR FFAA00

skinparam class {
  BackgroundColor METAL
  BorderColor Black
  ArrowColor Black
}

package "system" as target_system {

  entity "teams" as team <<M,MASTER_MARK_COLOR>> MAIN_ENTITY {
    + id [PK]
    --
    name
  }

  entity "comments" as comment <<T,TRANSACTION_MARK_COLOR>> MAIN_ENTITY_2 {
    + id [PK]
    --
    # team_id [FK(teams, id)]
    comment
    date
  }
}

team ----o{ comment

@enduml